### PR TITLE
And build script for Windows and build instructions

### PR DESCRIPTION
**Pull request by teodorlu**
Hello!

Great game. I've enjoyed it a lot, especially messing with the physics!

Also, congratulations for contributing to Teach Kids Code in Oslo! I'm currently contributing to a course for Elm, and last time we picked your game apart and made some changes. Hope you don't mind. The course material is in Norwegian, but feel free to have a look at [this funny Goole-translated version of the task](https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fteodorlu.github.io%2Fkodeklubben.github.io-elm%2Felm%2F6_lare_andres_spill%2F6_lare_andres_spill.html).

I needed easy building on Windows, hence the PR. I also described how to build the game in the README-file.

Teodor

### CODE REVIEW

**Review by stefankreitmayer — APPROVED** [review]
Brilliant! Thanks for this.

**Comment by stefankreitmayer** [comment]
Thank you Teodor. How exciting that you're using my game for teaching. I am flattered and deeply moved.

**Comment by teodorlu** [comment]
Hello! Slight update. This is probably the wrong place, but no matter.

1. After a file name cleanup, the link to the course site on your website broke. [New woking link][1].
2. I happened to [speak about this experience on Oslo Elm Day 2019][2]. If you're interested!

[1]: https://oppgaver.kidsakoder.no/elm/06_lare_andres_spill/06_lare_andres_spill
[2]: https://youtu.be/FSec8QmgEWo?t=701

Have a nice day!

**Comment by stefankreitmayer** [comment]
That's absolutely wonderful. I greatly enjoyed watching your talk on YouTube. Thrilled to hear it was such a success. I've added a link to your talk in the README - hope that's OK with you?

**Comment by teodorlu** [comment]
Absolutely :)

**Pull request merged**
